// Date: 26.09.2012 18:13:58
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package scythemod.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelMiniender extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Headwear;
    ModelRenderer Body;
    ModelRenderer RightArm;
    ModelRenderer LeftArm;
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;
  
  public ModelMiniender()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-4F, -8F, -4F, 8, 8, 8);
      Head.setRotationPoint(0F, 7F, 0F);
      Head.setTextureSize(64, 32);
      setRotation(Head, 0F, 0F, 0F);
      Headwear = new ModelRenderer(this, 0, 16);
      Headwear.addBox(-4F, -8F, -4F, 8, 8, 8);
      Headwear.setRotationPoint(0F, 7F, 0F);
      Headwear.setTextureSize(64, 32);
      setRotation(Headwear, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 40, 22);
      Body.addBox(-4F, 0F, -2F, 8, 6, 4);
      Body.setRotationPoint(0F, 7F, 0F);
      Body.setTextureSize(64, 32);
      setRotation(Body, 0F, 0F, 0F);
      RightArm = new ModelRenderer(this, 56, 0);
      RightArm.addBox(-1F, -2F, -1F, 2, 13, 2);
      RightArm.setRotationPoint(-5F, 9F, 0F);
      RightArm.setTextureSize(64, 32);
      setRotation(RightArm, 0F, 0F, 0F);
      LeftArm = new ModelRenderer(this, 56, 0);
      LeftArm.addBox(-1F, -2F, -1F, 2, 13, 2);
      LeftArm.setRotationPoint(5F, 9F, 0F);
      LeftArm.setTextureSize(64, 32);
      setRotation(LeftArm, 0F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 56, 0);
      RightLeg.addBox(-1F, 0F, -1F, 2, 11, 2);
      RightLeg.setRotationPoint(-2F, 13F, 0F);
      RightLeg.setTextureSize(64, 32);
      setRotation(RightLeg, 0F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 56, 0);
      LeftLeg.addBox(-1F, 0F, -1F, 2, 11, 2);
      LeftLeg.setRotationPoint(2F, 13F, 0F);
      LeftLeg.setTextureSize(64, 32);
      setRotation(LeftLeg, 0F, 0F, 0F);
  }
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.render(f5);
    Headwear.render(f5);
    Body.render(f5);
    RightArm.render(f5);
    LeftArm.render(f5);
    RightLeg.render(f5);
    LeftLeg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
	  this.Head.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Head.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Headwear.rotateAngleY = this.Head.rotateAngleY;
      this.Headwear.rotateAngleX = this.Head.rotateAngleX;
      this.RightArm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 2.0F * par2 * 0.5F;
      this.LeftArm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 2.0F * par2 * 0.5F;
      this.RightArm.rotateAngleZ = 0.0F;
      this.LeftArm.rotateAngleZ = 0.0F;
      this.RightLeg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      this.LeftLeg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      this.RightLeg.rotateAngleY = 0.0F;
      this.LeftLeg.rotateAngleY = 0.0F;
  }

}
