// Date: 23/05/2013 14:29:16
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package threeDitems_old.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class nugget extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
  
  public nugget()
  {
    textureWidth = 8;
    textureHeight = 4;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-0.7F, -1.7F, -1F, 2, 2, 2);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(8, 4);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, -0.1570796F, -0.2792527F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, -1F, 0F, 2, 1, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(8, 4);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, -0.3839724F, 0.1047198F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, -1F, -2F, 1, 1, 2);
      Shape3.setRotationPoint(0F, -1F, -1F);
      Shape3.setTextureSize(8, 4);
      Shape3.mirror = true;
      setRotation(Shape3, -0.7504916F, -0.3839724F, -0.0349066F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(-2F, 0F, 0F, 2, 1, 1);
      Shape4.setRotationPoint(0F, -1F, -0.5F);
      Shape4.setTextureSize(8, 4);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0.5235988F, 0.4537856F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, -1F, 0F, 2, 1, 1);
      Shape5.setRotationPoint(0F, -0.5F, -0.5F);
      Shape5.setTextureSize(8, 4);
      Shape5.mirror = true;
      setRotation(Shape5, 0.418879F, -0.418879F, -0.4363323F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(-2F, -1F, -1F, 2, 1, 1);
      Shape6.setRotationPoint(0F, 0F, 0F);
      Shape6.setTextureSize(8, 4);
      Shape6.mirror = true;
      setRotation(Shape6, -0.4886922F, -0.5061455F, -0.7330383F);
      Shape7 = new ModelRenderer(this, 0, 0);
      Shape7.addBox(-0.5F, -1F, 0F, 1, 1, 2);
      Shape7.setRotationPoint(0F, 0F, 0F);
      Shape7.setTextureSize(8, 4);
      Shape7.mirror = true;
      setRotation(Shape7, -0.418879F, -0.0872665F, 0.5061455F);
      Shape8 = new ModelRenderer(this, 0, 0);
      Shape8.addBox(-2.5F, -1F, -0.5F, 2, 1, 1);
      Shape8.setRotationPoint(0F, 0F, 0F);
      Shape8.setTextureSize(8, 4);
      Shape8.mirror = true;
      setRotation(Shape8, -0.1570796F, -0.6457718F, 0.9424778F);
      Shape9 = new ModelRenderer(this, 0, 0);
      Shape9.addBox(0F, -1F, -1F, 2, 1, 1);
      Shape9.setRotationPoint(0F, 0F, 0F);
      Shape9.setTextureSize(8, 4);
      Shape9.mirror = true;
      setRotation(Shape9, -0.7853982F, 0.5759587F, 0.5585054F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
