package redstone.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelThawer extends ModelBase
{
	//fields
	ModelRenderer back_right_handle;
	ModelRenderer bottom_middle_ring;
	ModelRenderer bottom_back_ring;
	ModelRenderer middle_left_ring;
	ModelRenderer top_middle_ring;
	ModelRenderer back_bottom_handle;
	ModelRenderer middle_right_barrel;
	ModelRenderer top_middle_ring2;
	ModelRenderer middle_front_left_ring;
	ModelRenderer Shape1;
	ModelRenderer middle_left_barrel;
	ModelRenderer top_left_barrel;
	ModelRenderer energy;
	ModelRenderer middle_right_ring;
	ModelRenderer front_bottom_ring;
	ModelRenderer front_middel_left_ring;
	ModelRenderer top_barrel;
	ModelRenderer back_left_handle;
	ModelRenderer back_top_ring_and_handle;
	ModelRenderer top_right_handle;
	ModelRenderer top_left_handle;
	ModelRenderer bottom_barrel;
	ModelRenderer top_left_barrel2;
	ModelRenderer middle_barrel;

	public ModelThawer()
	{
		textureWidth = 100;
		textureHeight = 75;

		back_right_handle = new ModelRenderer(this, 16, 0);
		back_right_handle.addBox(0F, 0F, 0F, 1, 4, 6);
		back_right_handle.setRotationPoint(0F, 0F, 5F);
		back_right_handle.setTextureSize(100, 75);
		back_right_handle.mirror = true;
		setRotation(back_right_handle, 0F, 0F, 0F);
		bottom_middle_ring = new ModelRenderer(this, 53, 0);
		bottom_middle_ring.addBox(0F, 0F, 0F, 4, 1, 1);
		bottom_middle_ring.setRotationPoint(1F, 4F, 2F);
		bottom_middle_ring.setTextureSize(100, 75);
		bottom_middle_ring.mirror = true;
		setRotation(bottom_middle_ring, 0F, 0F, 0F);
		bottom_back_ring = new ModelRenderer(this, 53, 0);
		bottom_back_ring.addBox(0F, 0F, 0F, 4, 1, 1);
		bottom_back_ring.setRotationPoint(1F, 4F, 5F);
		bottom_back_ring.setTextureSize(100, 75);
		bottom_back_ring.mirror = true;
		setRotation(bottom_back_ring, 0F, 0F, 0F);
		middle_left_ring = new ModelRenderer(this, 45, 0);
		middle_left_ring.addBox(0F, 0F, 0F, 1, 4, 1);
		middle_left_ring.setRotationPoint(5F, 0F, 2F);
		middle_left_ring.setTextureSize(100, 75);
		middle_left_ring.mirror = true;
		setRotation(middle_left_ring, 0F, 0F, 0F);
		top_middle_ring = new ModelRenderer(this, 53, 0);
		top_middle_ring.addBox(0F, 0F, 0F, 4, 1, 1);
		top_middle_ring.setRotationPoint(1F, -1F, 2F);
		top_middle_ring.setTextureSize(100, 75);
		top_middle_ring.mirror = true;
		setRotation(top_middle_ring, 0F, 0F, 0F);
		back_bottom_handle = new ModelRenderer(this, 32, 7);
		back_bottom_handle.addBox(0F, 0F, 0F, 2, 1, 3);
		back_bottom_handle.setRotationPoint(2F, 4F, 6F);
		back_bottom_handle.setTextureSize(100, 75);
		back_bottom_handle.mirror = true;
		setRotation(back_bottom_handle, 0F, 0F, 0F);
		middle_right_barrel = new ModelRenderer(this, 0, 37);
		middle_right_barrel.addBox(0F, 0F, 0F, 1, 2, 8);
		middle_right_barrel.setRotationPoint(0F, 1F, -11F);
		middle_right_barrel.setTextureSize(100, 75);
		middle_right_barrel.mirror = true;
		setRotation(middle_right_barrel, 0F, 0F, 0F);
		top_middle_ring2 = new ModelRenderer(this, 53, 0);
		top_middle_ring2.addBox(0F, 0F, 0F, 4, 1, 1);
		top_middle_ring2.setRotationPoint(1F, -1F, -1F);
		top_middle_ring2.setTextureSize(100, 75);
		top_middle_ring2.mirror = true;
		setRotation(top_middle_ring2, 0F, 0F, 0F);
		middle_front_left_ring = new ModelRenderer(this, 45, 0);
		middle_front_left_ring.addBox(0F, 0F, 0F, 1, 4, 1);
		middle_front_left_ring.setRotationPoint(0F, 0F, -1F);
		middle_front_left_ring.setTextureSize(100, 75);
		middle_front_left_ring.mirror = true;
		setRotation(middle_front_left_ring, 0F, 0F, 0F);
		Shape1 = new ModelRenderer(this, 31, 0);
		Shape1.addBox(0F, 0F, 0F, 4, 3, 2);
		Shape1.setRotationPoint(1F, 0F, -3F);
		Shape1.setTextureSize(100, 75);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		middle_left_barrel = new ModelRenderer(this, 0, 37);
		middle_left_barrel.addBox(0F, 0F, 0F, 1, 2, 8);
		middle_left_barrel.setRotationPoint(5F, 1F, -11F);
		middle_left_barrel.setTextureSize(100, 75);
		middle_left_barrel.mirror = true;
		setRotation(middle_left_barrel, 0F, 0F, 0F);
		top_left_barrel = new ModelRenderer(this, 0, 48);
		top_left_barrel.addBox(0F, 0F, 0F, 1, 1, 8);
		top_left_barrel.setRotationPoint(4F, 1F, -11F);
		top_left_barrel.setTextureSize(100, 75);
		top_left_barrel.mirror = true;
		setRotation(top_left_barrel, 0F, 0F, 0F);
		energy = new ModelRenderer(this, 73, 0);
		energy.addBox(0F, 0F, 0F, 4, 4, 6);
		energy.setRotationPoint(1F, 0F, -1F);
		energy.setTextureSize(100, 75);
		energy.mirror = true;
		setRotation(energy, 0F, 0F, 0F);
		middle_right_ring = new ModelRenderer(this, 45, 0);
		middle_right_ring.addBox(0F, 0F, 0F, 1, 4, 1);
		middle_right_ring.setRotationPoint(0F, 0F, 2F);
		middle_right_ring.setTextureSize(100, 75);
		middle_right_ring.mirror = true;
		setRotation(middle_right_ring, 0F, 0F, 0F);
		front_bottom_ring = new ModelRenderer(this, 53, 0);
		front_bottom_ring.addBox(0F, 0F, 0F, 4, 1, 1);
		front_bottom_ring.setRotationPoint(1F, 4F, -1F);
		front_bottom_ring.setTextureSize(100, 75);
		front_bottom_ring.mirror = true;
		setRotation(front_bottom_ring, 0F, 0F, 0F);
		front_middel_left_ring = new ModelRenderer(this, 45, 0);
		front_middel_left_ring.addBox(0F, 0F, 0F, 1, 4, 1);
		front_middel_left_ring.setRotationPoint(5F, 0F, -1F);
		front_middel_left_ring.setTextureSize(100, 75);
		front_middel_left_ring.mirror = true;
		setRotation(front_middel_left_ring, 0F, 0F, 0F);
		top_barrel = new ModelRenderer(this, 0, 62);
		top_barrel.addBox(0F, 0F, 0F, 4, 1, 8);
		top_barrel.setRotationPoint(1F, 0F, -11F);
		top_barrel.setTextureSize(100, 75);
		top_barrel.mirror = true;
		setRotation(top_barrel, 0F, 0F, 0F);
		back_left_handle = new ModelRenderer(this, 16, 0);
		back_left_handle.addBox(0F, 0F, 0F, 1, 4, 6);
		back_left_handle.setRotationPoint(5F, 0F, 5F);
		back_left_handle.setTextureSize(100, 75);
		back_left_handle.mirror = true;
		setRotation(back_left_handle, 0F, 0F, 0F);
		back_top_ring_and_handle = new ModelRenderer(this, 53, 8);
		back_top_ring_and_handle.addBox(0F, 0F, 0F, 4, 1, 2);
		back_top_ring_and_handle.setRotationPoint(1F, -1F, 5F);
		back_top_ring_and_handle.setTextureSize(100, 75);
		back_top_ring_and_handle.mirror = true;
		setRotation(back_top_ring_and_handle, 0F, 0F, 0F);
		top_right_handle = new ModelRenderer(this, 0, 0);
		top_right_handle.addBox(0F, 0F, 0F, 1, 1, 3);
		top_right_handle.setRotationPoint(1F, -1F, 7F);
		top_right_handle.setTextureSize(100, 75);
		top_right_handle.mirror = true;
		setRotation(top_right_handle, 0F, 0F, 0F);
		top_left_handle = new ModelRenderer(this, 0, 0);
		top_left_handle.addBox(0F, 0F, 0F, 1, 1, 3);
		top_left_handle.setRotationPoint(4F, -1F, 7F);
		top_left_handle.setTextureSize(100, 75);
		top_left_handle.mirror = true;
		setRotation(top_left_handle, 0F, 0F, 0F);
		bottom_barrel = new ModelRenderer(this, 0, 11);
		bottom_barrel.addBox(0F, 0F, 0F, 4, 1, 10);
		bottom_barrel.setRotationPoint(1F, 3F, -11F);
		bottom_barrel.setTextureSize(100, 75);
		bottom_barrel.mirror = true;
		setRotation(bottom_barrel, 0F, 0F, 0F);
		top_left_barrel2 = new ModelRenderer(this, 0, 48);
		top_left_barrel2.addBox(0F, 0F, 0F, 1, 1, 8);
		top_left_barrel2.setRotationPoint(1F, 1F, -11F);
		top_left_barrel2.setTextureSize(100, 75);
		top_left_barrel2.mirror = true;
		setRotation(top_left_barrel2, 0F, 0F, 0F);
		middle_barrel = new ModelRenderer(this, 0, 23);
		middle_barrel.addBox(0F, 0F, 0F, 2, 1, 10);
		middle_barrel.setRotationPoint(2F, 2F, -11F);
		middle_barrel.setTextureSize(100, 75);
		middle_barrel.mirror = true;
		setRotation(middle_barrel, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		back_right_handle.render(f5);
		bottom_middle_ring.render(f5);
		bottom_back_ring.render(f5);
		middle_left_ring.render(f5);
		top_middle_ring.render(f5);
		back_bottom_handle.render(f5);
		middle_right_barrel.render(f5);
		top_middle_ring2.render(f5);
		middle_front_left_ring.render(f5);
		Shape1.render(f5);
		middle_left_barrel.render(f5);
		top_left_barrel.render(f5);
		energy.render(f5);
		middle_right_ring.render(f5);
		front_bottom_ring.render(f5);
		front_middel_left_ring.render(f5);
		top_barrel.render(f5);
		back_left_handle.render(f5);
		back_top_ring_and_handle.render(f5);
		top_right_handle.render(f5);
		top_left_handle.render(f5);
		bottom_barrel.render(f5);
		top_left_barrel2.render(f5);
		middle_barrel.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}