package redstone.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGunGreen extends ModelBase
{
	//fields
	ModelRenderer top_right_energy_case;
	ModelRenderer top_right_barrel;
	ModelRenderer bottom_barrel;
	ModelRenderer bottom_right_barrel;
	ModelRenderer top_right_barrel_;
	ModelRenderer top_back_base;
	ModelRenderer top_middle_barrel;
	ModelRenderer bottom_left_barrel;
	ModelRenderer front_energy;
	ModelRenderer middle_barrel;
	ModelRenderer top_left_barrel;
	ModelRenderer back_left_enrgy;
	ModelRenderer top_left_energy_case;
	ModelRenderer bottom_right_base;
	ModelRenderer top_middle_base;
	ModelRenderer bottom_right_back;
	ModelRenderer bottom_right_energy_case;
	ModelRenderer right_long_energy;
	ModelRenderer back_bottom_left_energy_case;
	ModelRenderer middle_back_energy_case;
	ModelRenderer middle_left_energy_case;
	ModelRenderer bottom_left_energy_case;
	ModelRenderer bottom_left_base;
	ModelRenderer top_left_barrel_;

	public ModelGunGreen()
	{
		textureWidth = 64;
		textureHeight = 32;

		top_right_energy_case = new ModelRenderer(this, 36, 18);
		top_right_energy_case.addBox(0F, 0F, 0F, 1, 1, 13);
		top_right_energy_case.setRotationPoint(0F, 0F, 1F);
		top_right_energy_case.setTextureSize(64, 32);
		top_right_energy_case.mirror = true;
		setRotation(top_right_energy_case, 0F, 0F, 0F);
		top_right_barrel = new ModelRenderer(this, 0, 29);
		top_right_barrel.addBox(0F, 0F, 0F, 1, 2, 1);
		top_right_barrel.setRotationPoint(0F, 0F, 0F);
		top_right_barrel.setTextureSize(64, 32);
		top_right_barrel.mirror = true;
		setRotation(top_right_barrel, 0F, 0F, 0F);
		bottom_barrel = new ModelRenderer(this, 4, 25);
		bottom_barrel.addBox(0F, 0F, 0F, 3, 1, 6);
		bottom_barrel.setRotationPoint(2F, 4F, 0F);
		bottom_barrel.setTextureSize(64, 32);
		bottom_barrel.mirror = true;
		setRotation(bottom_barrel, 0F, 0F, 0F);
		bottom_right_barrel = new ModelRenderer(this, 0, 29);
		bottom_right_barrel.addBox(0F, 0F, 0F, 1, 2, 1);
		bottom_right_barrel.setRotationPoint(1F, 2F, 0F);
		bottom_right_barrel.setTextureSize(64, 32);
		bottom_right_barrel.mirror = true;
		setRotation(bottom_right_barrel, 0F, 0F, 0F);
		top_right_barrel_ = new ModelRenderer(this, 48, 11);
		top_right_barrel_.addBox(0F, 0F, 0F, 2, 1, 6);
		top_right_barrel_.setRotationPoint(1F, -1F, 0F);
		top_right_barrel_.setTextureSize(64, 32);
		top_right_barrel_.mirror = true;
		setRotation(top_right_barrel_, 0F, 0F, 0F);
		top_back_base = new ModelRenderer(this, 38, 0);
		top_back_base.addBox(0F, 0F, 0F, 5, 1, 8);
		top_back_base.setRotationPoint(1F, -1F, 6F);
		top_back_base.setTextureSize(64, 32);
		top_back_base.mirror = true;
		setRotation(top_back_base, 0F, 0F, 0F);
		top_middle_barrel = new ModelRenderer(this, 0, 27);
		top_middle_barrel.addBox(0F, 0F, 0F, 1, 1, 1);
		top_middle_barrel.setRotationPoint(3F, 0F, 0F);
		top_middle_barrel.setTextureSize(64, 32);
		top_middle_barrel.mirror = true;
		setRotation(top_middle_barrel, 0F, 0F, 0F);
		bottom_left_barrel = new ModelRenderer(this, 0, 29);
		bottom_left_barrel.addBox(0F, 0F, 0F, 1, 2, 1);
		bottom_left_barrel.setRotationPoint(5F, 2F, 0F);
		bottom_left_barrel.setTextureSize(64, 32);
		bottom_left_barrel.mirror = true;
		setRotation(bottom_left_barrel, 0F, 0F, 0F);
		front_energy = new ModelRenderer(this, 22, 27);
		front_energy.addBox(0F, 0F, 0F, 5, 4, 1);
		front_energy.setRotationPoint(1F, 0F, 1F);
		front_energy.setTextureSize(64, 32);
		front_energy.mirror = true;
		setRotation(front_energy, 0F, 0F, 0F);
		middle_barrel = new ModelRenderer(this, 0, 23);
		middle_barrel.addBox(0F, 0F, 0F, 5, 1, 1);
		middle_barrel.setRotationPoint(1F, 1F, 0F);
		middle_barrel.setTextureSize(64, 32);
		middle_barrel.mirror = true;
		setRotation(middle_barrel, 0F, 0F, 0F);
		top_left_barrel = new ModelRenderer(this, 0, 29);
		top_left_barrel.addBox(0F, 0F, 0F, 1, 2, 1);
		top_left_barrel.setRotationPoint(6F, 0F, 0F);
		top_left_barrel.setTextureSize(64, 32);
		top_left_barrel.mirror = true;
		setRotation(top_left_barrel, 0F, 0F, 0F);
		back_left_enrgy = new ModelRenderer(this, 0, 19);
		back_left_enrgy.addBox(0F, 0F, 0F, 1, 2, 2);
		back_left_enrgy.setRotationPoint(1F, 1F, 11F);
		back_left_enrgy.setTextureSize(64, 32);
		back_left_enrgy.mirror = true;
		setRotation(back_left_enrgy, 0F, 0F, 0F);
		top_left_energy_case = new ModelRenderer(this, 36, 18);
		top_left_energy_case.addBox(0F, 0F, 0F, 1, 1, 13);
		top_left_energy_case.setRotationPoint(6F, 0F, 1F);
		top_left_energy_case.setTextureSize(64, 32);
		top_left_energy_case.mirror = true;
		setRotation(top_left_energy_case, 0F, 0F, 0F);
		bottom_right_base = new ModelRenderer(this, 15, 15);
		bottom_right_base.addBox(0F, 0F, 0F, 1, 1, 9);
		bottom_right_base.setRotationPoint(1F, 3F, 2F);
		bottom_right_base.setTextureSize(64, 32);
		bottom_right_base.mirror = true;
		setRotation(bottom_right_base, 0F, 0F, 0F);
		top_middle_base = new ModelRenderer(this, 0, 14);
		top_middle_base.addBox(0F, 0F, 0F, 1, 1, 4);
		top_middle_base.setRotationPoint(3F, 0F, 2F);
		top_middle_base.setTextureSize(64, 32);
		top_middle_base.mirror = true;
		setRotation(top_middle_base, 0F, 0F, 0F);
		bottom_right_back = new ModelRenderer(this, 1, 15);
		bottom_right_back.addBox(0F, 0F, 0F, 1, 1, 3);
		bottom_right_back.setRotationPoint(0F, 3F, 11F);
		bottom_right_back.setTextureSize(64, 32);
		bottom_right_back.mirror = true;
		setRotation(bottom_right_back, 0F, 0F, 0F);
		bottom_right_energy_case = new ModelRenderer(this, 0, 0);
		bottom_right_energy_case.addBox(0F, 0F, 0F, 1, 1, 10);
		bottom_right_energy_case.setRotationPoint(0F, 2F, 1F);
		bottom_right_energy_case.setTextureSize(64, 32);
		bottom_right_energy_case.mirror = true;
		setRotation(bottom_right_energy_case, 0F, 0F, 0F);
		right_long_energy = new ModelRenderer(this, 15, 15);
		right_long_energy.addBox(0F, 0F, 0F, 1, 1, 9);
		right_long_energy.setRotationPoint(1F, 1F, 2F);
		right_long_energy.setTextureSize(64, 32);
		right_long_energy.mirror = true;
		setRotation(right_long_energy, 0F, 0F, 0F);
		back_bottom_left_energy_case = new ModelRenderer(this, 1, 15);
		back_bottom_left_energy_case.addBox(0F, 0F, 0F, 1, 1, 3);
		back_bottom_left_energy_case.setRotationPoint(6F, 3F, 11F);
		back_bottom_left_energy_case.setTextureSize(64, 32);
		back_bottom_left_energy_case.mirror = true;
		setRotation(back_bottom_left_energy_case, 0F, 0F, 0F);
		middle_back_energy_case = new ModelRenderer(this, 28, 0);
		middle_back_energy_case.addBox(0F, 0F, 0F, 1, 2, 2);
		middle_back_energy_case.setRotationPoint(5F, 1F, 11F);
		middle_back_energy_case.setTextureSize(64, 32);
		middle_back_energy_case.mirror = true;
		setRotation(middle_back_energy_case, 0F, 0F, 0F);
		middle_left_energy_case = new ModelRenderer(this, 15, 15);
		middle_left_energy_case.addBox(0F, 0F, 0F, 1, 1, 9);
		middle_left_energy_case.setRotationPoint(5F, 1F, 2F);
		middle_left_energy_case.setTextureSize(64, 32);
		middle_left_energy_case.mirror = true;
		setRotation(middle_left_energy_case, 0F, 0F, 0F);
		bottom_left_energy_case = new ModelRenderer(this, 0, 0);
		bottom_left_energy_case.addBox(0F, 0F, 0F, 1, 1, 10);
		bottom_left_energy_case.setRotationPoint(6F, 2F, 1F);
		bottom_left_energy_case.setTextureSize(64, 32);
		bottom_left_energy_case.mirror = true;
		setRotation(bottom_left_energy_case, 0F, 0F, 0F);
		bottom_left_base = new ModelRenderer(this, 15, 15);
		bottom_left_base.addBox(0F, 0F, 0F, 1, 1, 9);
		bottom_left_base.setRotationPoint(5F, 3F, 2F);
		bottom_left_base.setTextureSize(64, 32);
		bottom_left_base.mirror = true;
		setRotation(bottom_left_base, 0F, 0F, 0F);
		top_left_barrel_ = new ModelRenderer(this, 48, 11);
		top_left_barrel_.addBox(0F, 0F, 0F, 2, 1, 6);
		top_left_barrel_.setRotationPoint(4F, -1F, 0F);
		top_left_barrel_.setTextureSize(64, 32);
		top_left_barrel_.mirror = true;
		setRotation(top_left_barrel_, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		top_right_energy_case.render(f5);
		top_right_barrel.render(f5);
		bottom_barrel.render(f5);
		bottom_right_barrel.render(f5);
		top_right_barrel_.render(f5);
		top_back_base.render(f5);
		top_middle_barrel.render(f5);
		bottom_left_barrel.render(f5);
		front_energy.render(f5);
		middle_barrel.render(f5);
		top_left_barrel.render(f5);
		back_left_enrgy.render(f5);
		top_left_energy_case.render(f5);
		bottom_right_base.render(f5);
		top_middle_base.render(f5);
		bottom_right_back.render(f5);
		bottom_right_energy_case.render(f5);
		right_long_energy.render(f5);
		back_bottom_left_energy_case.render(f5);
		middle_back_energy_case.render(f5);
		middle_left_energy_case.render(f5);
		bottom_left_energy_case.render(f5);
		bottom_left_base.render(f5);
		top_left_barrel_.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}