// Date: 21/08/2013 18:03:07
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package berryBushes.te;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class bush extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape14;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
  
  public bush()
  {
    textureWidth = 30;
    textureHeight = 16;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 2, 1, 2);
      Shape1.setRotationPoint(0F, 23F, 0F);
      Shape1.setTextureSize(60, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 2, 2, 2);
      Shape2.setRotationPoint(-1F, 21F, 0F);
      Shape2.setTextureSize(60, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 2, 2, 2);
      Shape3.setRotationPoint(0F, 19F, 0F);
      Shape3.setTextureSize(60, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape4.setRotationPoint(0F, 23F, -1F);
      Shape4.setTextureSize(60, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape5.setRotationPoint(2F, 23F, 0F);
      Shape5.setTextureSize(60, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(1F, 0F, 2F, 1, 1, 1);
      Shape6.setRotationPoint(0F, 23F, 0F);
      Shape6.setTextureSize(60, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 0);
      Shape7.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape7.setRotationPoint(-2F, 23F, 0F);
      Shape7.setTextureSize(60, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 0);
      Shape8.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape8.setRotationPoint(-2F, 23F, 2F);
      Shape8.setTextureSize(60, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 4);
      Shape9.addBox(-2F, 0F, -1F, 7, 6, 4);
      Shape9.setRotationPoint(0F, 13F, 0F);
      Shape9.setTextureSize(60, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 4);
      Shape10.addBox(-4F, 0.05F, -5F, 5, 6, 6);
      Shape10.setRotationPoint(3F, 13F, 3F);
      Shape10.setTextureSize(60, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 4);
      Shape11.addBox(0F, 0F, 0F, 7, 4, 6);
      Shape11.setRotationPoint(-2F, 14F, -2F);
      Shape11.setTextureSize(60, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 4);
      Shape12.addBox(-1F, 0F, -3F, 5, 4, 8);
      Shape12.setRotationPoint(0F, 14F, 0F);
      Shape12.setTextureSize(60, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 0, 4);
      Shape13.addBox(-3F, -3F, -1F, 9, 4, 4);
      Shape13.setRotationPoint(0F, 17F, 0F);
      Shape13.setTextureSize(60, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 0, 4);
      Shape15.addBox(-10F, 0F, 0F, 11, 2, 4);
      Shape15.setRotationPoint(6F, 15F, -1F);
      Shape15.setTextureSize(60, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 4);
      Shape16.addBox(0F, 0F, -4F, 5, 2, 10);
      Shape16.setRotationPoint(-1F, 15F, 0F);
      Shape16.setTextureSize(60, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 5);
      Shape14.addBox(0F, 0F, -5F, 9, 2, 6);
      Shape14.setRotationPoint(-3F, 15F, 3F);
      Shape14.setTextureSize(60, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 4);
      Shape17.addBox(0F, 0F, -7F, 7, 2, 8);
      Shape17.setRotationPoint(-2F, 15F, 4F);
      Shape17.setTextureSize(60, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 0, 0);
      Shape18.addBox(1F, 0F, 0F, 1, 1, 1);
      Shape18.setRotationPoint(0F, 20F, -1F);
      Shape18.setTextureSize(60, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 0, 0);
      Shape19.addBox(-1F, 0F, 0F, 1, 1, 1);
      Shape19.setRotationPoint(3F, 19F, -2F);
      Shape19.setTextureSize(60, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 0, 0);
      Shape20.addBox(-1F, 0F, 0F, 1, 1, 1);
      Shape20.setRotationPoint(0F, 19F, 2F);
      Shape20.setTextureSize(60, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 0, 0);
      Shape21.addBox(2F, 0F, 1F, 1, 1, 1);
      Shape21.setRotationPoint(0F, 20F, 0F);
      Shape21.setTextureSize(60, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 0, 0);
      Shape22.addBox(2F, 0F, 1F, 1, 1, 1);
      Shape22.setRotationPoint(0F, 19F, 1F);
      Shape22.setTextureSize(60, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape14.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
  }
  
  public void render(float f5){
	    Shape1.render(f5);
	    Shape2.render(f5);
	    Shape3.render(f5);
	    Shape4.render(f5);
	    Shape5.render(f5);
	    Shape6.render(f5);
	    Shape7.render(f5);
	    Shape8.render(f5);
	    Shape9.render(f5);
	    Shape10.render(f5);
	    Shape11.render(f5);
	    Shape12.render(f5);
	    Shape13.render(f5);
	    Shape15.render(f5);
	    Shape16.render(f5);
	    Shape14.render(f5);
	    Shape17.render(f5);
	    Shape18.render(f5);
	    Shape19.render(f5);
	    Shape20.render(f5);
	    Shape21.render(f5);
	    Shape22.render(f5);
  }
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }


}
