// Date: 05/05/2013 12:35:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package threeDitems.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class spade extends ModelBase
{
	//fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;

	public spade()
	{
		textureWidth = 28;
		textureHeight = 14;

		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, -4F, 1, 1, 13);
		Shape1.setRotationPoint(0F, 0F, 0F);
		Shape1.setTextureSize(28, 14);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(0F, -2F, 8F, 1, 2, 1);
		Shape2.setRotationPoint(0F, 0F, 0F);
		Shape2.setTextureSize(28, 14);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0.2094395F);
		Shape3 = new ModelRenderer(this, 0, 0);
		Shape3.addBox(0F, 0F, 8F, 1, 2, 1);
		Shape3.setRotationPoint(0F, 1F, 0F);
		Shape3.setTextureSize(28, 14);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 0F, -0.2094395F);
		Shape4 = new ModelRenderer(this, 0, 0);
		Shape4.addBox(0F, -2.5F, 9F, 1, 3, 3);
		Shape4.setRotationPoint(0F, 0F, 0F);
		Shape4.setTextureSize(28, 14);
		Shape4.mirror = true;
		setRotation(Shape4, 0F, 0F, 0.2094395F);
		Shape5 = new ModelRenderer(this, 0, 0);
		Shape5.addBox(0F, -0.5F, 9F, 1, 3, 3);
		Shape5.setRotationPoint(0F, 1F, 0F);
		Shape5.setTextureSize(28, 14);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 0F, -0.2094395F);
		Shape6 = new ModelRenderer(this, 12, 10);
		Shape6.addBox(0F, -1F, -5F, 1, 3, 1);
		Shape6.setRotationPoint(0F, 0F, 0F);
		Shape6.setTextureSize(28, 14);
		Shape6.mirror = true;
		setRotation(Shape6, 0F, 0F, 0F);
		Shape7 = new ModelRenderer(this, 0, 6);
		Shape7.addBox(0F, -2F, 12F, 1, 2, 1);
		Shape7.setRotationPoint(0F, 0F, 0F);
		Shape7.setTextureSize(28, 14);
		Shape7.mirror = true;
		setRotation(Shape7, 0F, 0F, 0.2094395F);
		Shape8 = new ModelRenderer(this, 0, 7);
		Shape8.addBox(0F, -0.5F, 12F, 1, 1, 1);
		Shape8.setRotationPoint(0F, 0F, 0F);
		Shape8.setTextureSize(28, 14);
		Shape8.mirror = true;
		setRotation(Shape8, 0F, 0F, 0.2094395F);
		Shape9 = new ModelRenderer(this, 0, 7);
		Shape9.addBox(0F, 0F, 12F, 1, 2, 1);
		Shape9.setRotationPoint(0F, 1F, 0F);
		Shape9.setTextureSize(28, 14);
		Shape9.mirror = true;
		setRotation(Shape9, 0F, 0F, -0.2094395F);
		Shape10 = new ModelRenderer(this, 0, 7);
		Shape10.addBox(0F, -0.5F, 12F, 1, 1, 1);
		Shape10.setRotationPoint(0F, 1F, 0F);
		Shape10.setTextureSize(28, 14);
		Shape10.mirror = true;
		setRotation(Shape10, 0F, 0F, -0.2094395F);
		Shape11 = new ModelRenderer(this, 0, 0);
		Shape11.addBox(0F, -1.5F, 13F, 1, 2, 1);
		Shape11.setRotationPoint(0F, 0F, 0F);
		Shape11.setTextureSize(28, 14);
		Shape11.mirror = true;
		setRotation(Shape11, 0F, 0F, 0.2094395F);
		Shape12 = new ModelRenderer(this, 0, 0);
		Shape12.addBox(0F, -0.5F, 13F, 1, 2, 1);
		Shape12.setRotationPoint(0F, 1F, 0F);
		Shape12.setTextureSize(28, 14);
		Shape12.mirror = true;
		setRotation(Shape12, 0F, 0F, -0.2094395F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
		Shape6.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	} 
}
