// Date: 06/05/2013 12:29:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package threeDitems.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class bed extends ModelBase
{
	//fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;

	public bed()
	{
		textureWidth = 96;
		textureHeight = 50;

		Shape1 = new ModelRenderer(this, 0, 3);
		Shape1.addBox(-16F, -4F, -8F, 32, 6, 16);
		Shape1.setRotationPoint(0F, 0F, 0F);
		Shape1.setTextureSize(96, 50);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, -16);
		Shape2.addBox(-16F, -2F, -8F, 32, 3, 16);
		Shape2.setRotationPoint(0F, 4F, 0F);
		Shape2.setTextureSize(96, 50);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1.render(f5);
		Shape2.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}